// Generated by generate-gallery.py. Do not edit by hand.
window.galleryItems = [
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g2/preview.webm",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g3/preview.webm",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g4/preview.webm",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g5/preview.jpg",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "demo"
    ],
    "shortDescription": "Night/day sky generator written in OpenGL/LWJGL",
    "longDescription": "Night/day sky generator written in OpenGL/LWJGL\n\nSource: https://github.com/fqqf/stars-gen-cloudy",
    "preview": "gallery/g7/preview.webm",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g8/preview.jpg",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g9/preview.jpg",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "animation"
    ],
    "shortDescription": "Logo animation for MART in 2017",
    "longDescription": "Logo animation for MART in 2017\nMy first paid vector animation\n\nLooking back i completely dislike how it turned out, i could've done it way better.",
    "preview": "gallery/g10/preview.webm",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "software"
    ],
    "shortDescription": "Dynamic analysis tool for identifying instruction pointers processing pattern in memory",
    "longDescription": "Dynamic analysis tool for identifying instruction pointers processing pattern in memory \nSource: https://miracula.space/files/bingrep.zip",
    "preview": "gallery/g11/preview.png",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "game"
    ],
    "shortDescription": "Short platformer in white-black tones",
    "longDescription": "Short platformer in white-black tones\n\nMade in 2021 with uheartbeast\n\nSource: https://icx.itch.io/melancholy-fight",
    "preview": "gallery/g12/preview.mp4",
    "media": [],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "game"
    ],
    "shortDescription": "2D runner with platforming. Defeat and tame monsters, find new locations",
    "longDescription": "2D runner with platforming. Defeat and tame monsters, find new locations\n\nPrevious version of game was lost, all media that exist of it is here. \nIn case i find a way to restore data, i'll publish updated versions.",
    "preview": "gallery/g13/preview.mp4",
    "media": [
      "gallery/g13/2.jpg",
      "gallery/g13/3.jpg",
      "gallery/g13/4.jpg"
    ],
    "hidePreview": false
  },
  {
    "title": "Drumir",
    "tags": [
      "demo"
    ],
    "shortDescription": "World exploration multiplayer game based on DCC by Matt Dinniman",
    "longDescription": "World exploration multiplayer game based on DCC by Matt Dinniman\n\nIn development right now, looking for 2nd artist for this project.\n2026",
    "preview": "gallery/g14/preview.webm",
    "media": [
      "gallery/g14/1.webm",
      "gallery/g14/2.mp4"
    ],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "game"
    ],
    "shortDescription": "Snippet of a game for Godot Wild Jam #51",
    "longDescription": "",
    "preview": "gallery/g15/preview.gif",
    "media": [
      "gallery/g15/1.mp4"
    ],
    "hidePreview": true
  },
  {
    "title": "",
    "tags": [
      "software"
    ],
    "shortDescription": "3D hyperrealistic maze generation backtracking algorithm in Unreal Engine 5",
    "longDescription": "3D hyperrealistic maze generation backtracking algorithm in Unreal Engine 5.\n\nFeed it an image, and it spits out 3d realistic maze based on that image.\n\nSource: https://github.com/fqqf/backtracking-3d-generator",
    "preview": "gallery/g16/preview.png",
    "media": [
      "gallery/g16/1.jpg",
      "gallery/g16/2.jpg"
    ],
    "hidePreview": false
  },
  {
    "title": "",
    "tags": [
      "demo"
    ],
    "shortDescription": "Demo of rimworld-like game made to test AI for Drumir",
    "longDescription": "Demo of rimworld-like game made to test AI for Drumir\n\nClosed source.",
    "preview": "gallery/g18/preview.mp4",
    "media": [
      "gallery/g18/1.jpg",
      "gallery/g18/2.mp4"
    ],
    "hidePreview": false
  }
];
