// Generated by generate-gallery.py. Do not edit by hand.
window.galleryItems = [
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g2/preview.mp4",
    "fullsizePreview": "gallery/g2/fullsize_preview.webm",
    "media": [],
    "previewAsset": {
      "src": "gallery/g2/preview.mp4",
      "kind": "video",
      "width": 320,
      "height": 230,
      "wide": "gallery/g2/opt/preview-320.mp4",
      "wideW": 320,
      "poster": "gallery/g2/opt/preview-poster.webp",
      "thumb": "gallery/g2/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g2/fullsize_preview.webm",
      "kind": "video",
      "width": 320,
      "height": 230,
      "poster": "gallery/g2/opt/fullsize-poster.webp",
      "thumb": "gallery/g2/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g3/preview.mp4",
    "fullsizePreview": "gallery/g3/fullsize_preview.webm",
    "media": [],
    "previewAsset": {
      "src": "gallery/g3/preview.mp4",
      "kind": "video",
      "width": 320,
      "height": 268,
      "wide": "gallery/g3/opt/preview-320.mp4",
      "wideW": 320,
      "poster": "gallery/g3/opt/preview-poster.webp",
      "thumb": "gallery/g3/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g3/fullsize_preview.webm",
      "kind": "video",
      "width": 320,
      "height": 268,
      "poster": "gallery/g3/opt/fullsize-poster.webp",
      "thumb": "gallery/g3/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g5/preview.jpg",
    "fullsizePreview": "",
    "media": [],
    "previewAsset": {
      "src": "gallery/g5/preview.jpg",
      "kind": "image",
      "width": 1270,
      "height": 686,
      "wide": "gallery/g5/opt/preview-960.webp",
      "wideW": 960,
      "narrow": "gallery/g5/opt/preview-640.webp",
      "narrowW": 640,
      "thumb": "gallery/g5/opt/preview-thumb.webp"
    },
    "fullsizeAsset": null,
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g6/preview.mp4",
    "fullsizePreview": "gallery/g6/fullsize_preview.webm",
    "media": [],
    "previewAsset": {
      "src": "gallery/g6/preview.mp4",
      "kind": "video",
      "width": 320,
      "height": 180,
      "wide": "gallery/g6/opt/preview-320.mp4",
      "wideW": 320,
      "poster": "gallery/g6/opt/preview-poster.webp",
      "thumb": "gallery/g6/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g6/fullsize_preview.webm",
      "kind": "video",
      "width": 320,
      "height": 180,
      "poster": "gallery/g6/opt/fullsize-poster.webp",
      "thumb": "gallery/g6/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "demo"
    ],
    "shortDescription": "Night/day sky generator written in OpenGL/LWJGL",
    "longDescription": "Night/day sky generator written in OpenGL/LWJGL\n\nSource: https://github.com/fqqf/stars-gen-cloudy",
    "preview": "gallery/g7/preview.mp4",
    "fullsizePreview": "gallery/g7/fullsize_preview.webm",
    "media": [],
    "previewAsset": {
      "src": "gallery/g7/preview.mp4",
      "kind": "video",
      "width": 1632,
      "height": 948,
      "wide": "gallery/g7/opt/preview-960.mp4",
      "wideW": 960,
      "narrow": "gallery/g7/opt/preview-640.mp4",
      "narrowW": 640,
      "poster": "gallery/g7/opt/preview-poster.webp",
      "thumb": "gallery/g7/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g7/fullsize_preview.webm",
      "kind": "video",
      "width": 1632,
      "height": 948,
      "poster": "gallery/g7/opt/fullsize-poster.webp",
      "thumb": "gallery/g7/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g8/preview.jpg",
    "fullsizePreview": "",
    "media": [],
    "previewAsset": {
      "src": "gallery/g8/preview.jpg",
      "kind": "image",
      "width": 1149,
      "height": 629,
      "wide": "gallery/g8/opt/preview-960.webp",
      "wideW": 960,
      "narrow": "gallery/g8/opt/preview-640.webp",
      "narrowW": 640,
      "thumb": "gallery/g8/opt/preview-thumb.webp"
    },
    "fullsizeAsset": null,
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "art"
    ],
    "shortDescription": "",
    "longDescription": "",
    "preview": "gallery/g9/preview.jpg",
    "fullsizePreview": "",
    "media": [],
    "previewAsset": {
      "src": "gallery/g9/preview.jpg",
      "kind": "image",
      "width": 1280,
      "height": 720,
      "wide": "gallery/g9/opt/preview-960.webp",
      "wideW": 960,
      "narrow": "gallery/g9/opt/preview-640.webp",
      "narrowW": 640,
      "thumb": "gallery/g9/opt/preview-thumb.webp"
    },
    "fullsizeAsset": null,
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "animation"
    ],
    "shortDescription": "Logo animation for MART in 2017",
    "longDescription": "Logo animation for MART in 2017\nMy first paid vector animation\n\nLooking back i completely dislike how it turned out, i could've done it way better.",
    "preview": "gallery/g10/preview.mp4",
    "fullsizePreview": "gallery/g10/fullsize_preview.webm",
    "media": [],
    "previewAsset": {
      "src": "gallery/g10/preview.mp4",
      "kind": "video",
      "width": 1168,
      "height": 800,
      "wide": "gallery/g10/opt/preview-960.mp4",
      "wideW": 960,
      "narrow": "gallery/g10/opt/preview-640.mp4",
      "narrowW": 640,
      "poster": "gallery/g10/opt/preview-poster.webp",
      "thumb": "gallery/g10/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g10/fullsize_preview.webm",
      "kind": "video",
      "width": 1168,
      "height": 800,
      "poster": "gallery/g10/opt/fullsize-poster.webp",
      "thumb": "gallery/g10/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "software"
    ],
    "shortDescription": "Dynamic analysis tool for identifying instruction pointers processing pattern in memory",
    "longDescription": "Dynamic analysis tool for identifying instruction pointers processing pattern in memory \nSource: https://miracula.space/files/bingrep.zip",
    "preview": "gallery/g11/preview.png",
    "fullsizePreview": "",
    "media": [],
    "previewAsset": {
      "src": "gallery/g11/preview.png",
      "kind": "image",
      "width": 965,
      "height": 846,
      "wide": "gallery/g11/opt/preview-960.webp",
      "wideW": 960,
      "narrow": "gallery/g11/opt/preview-640.webp",
      "narrowW": 640,
      "thumb": "gallery/g11/opt/preview-thumb.webp"
    },
    "fullsizeAsset": null,
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "game"
    ],
    "shortDescription": "Short platformer in white-black tones",
    "longDescription": "Short platformer in white-black tones\n\nMade in 2021 with uheartbeast\n\nSource: https://icx.itch.io/melancholy-fight",
    "preview": "gallery/g12/preview.mp4",
    "fullsizePreview": "gallery/g12/fullsize_preview.mp4",
    "media": [],
    "previewAsset": {
      "src": "gallery/g12/preview.mp4",
      "kind": "video",
      "width": 1272,
      "height": 712,
      "wide": "gallery/g12/opt/preview-960.mp4",
      "wideW": 960,
      "narrow": "gallery/g12/opt/preview-640.mp4",
      "narrowW": 640,
      "poster": "gallery/g12/opt/preview-poster.webp",
      "thumb": "gallery/g12/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g12/fullsize_preview.mp4",
      "kind": "video",
      "width": 1272,
      "height": 712,
      "poster": "gallery/g12/opt/fullsize-poster.webp",
      "thumb": "gallery/g12/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "game"
    ],
    "shortDescription": "2D runner with platforming. Defeat and tame monsters, find new locations",
    "longDescription": "2D runner with platforming. Defeat and tame monsters, find new locations\n\nPrevious version of game was lost, all media that exist of it is here. \nIn case i find a way to restore data, i'll publish updated versions.",
    "preview": "gallery/g13/preview.mp4",
    "fullsizePreview": "gallery/g13/fullsize_preview.mp4",
    "media": [
      "gallery/g13/2.jpg",
      "gallery/g13/3.jpg",
      "gallery/g13/4.jpg"
    ],
    "previewAsset": {
      "src": "gallery/g13/preview.mp4",
      "kind": "video",
      "width": 1392,
      "height": 592,
      "wide": "gallery/g13/opt/preview-960.mp4",
      "wideW": 960,
      "narrow": "gallery/g13/opt/preview-640.mp4",
      "narrowW": 640,
      "poster": "gallery/g13/opt/preview-poster.webp",
      "thumb": "gallery/g13/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g13/fullsize_preview.mp4",
      "kind": "video",
      "width": 1392,
      "height": 592,
      "poster": "gallery/g13/opt/fullsize-poster.webp",
      "thumb": "gallery/g13/opt/fullsize-thumb.webp"
    },
    "mediaAssets": [
      {
        "src": "gallery/g13/2.jpg",
        "kind": "image",
        "width": 1162,
        "height": 618,
        "wide": "gallery/g13/opt/m1-960.webp",
        "wideW": 960,
        "narrow": "gallery/g13/opt/m1-640.webp",
        "narrowW": 640,
        "thumb": "gallery/g13/opt/m1-thumb.webp"
      },
      {
        "src": "gallery/g13/3.jpg",
        "kind": "image",
        "width": 1280,
        "height": 607,
        "wide": "gallery/g13/opt/m2-960.webp",
        "wideW": 960,
        "narrow": "gallery/g13/opt/m2-640.webp",
        "narrowW": 640,
        "thumb": "gallery/g13/opt/m2-thumb.webp"
      },
      {
        "src": "gallery/g13/4.jpg",
        "kind": "image",
        "width": 1280,
        "height": 420,
        "wide": "gallery/g13/opt/m3-960.webp",
        "wideW": 960,
        "narrow": "gallery/g13/opt/m3-640.webp",
        "narrowW": 640,
        "thumb": "gallery/g13/opt/m3-thumb.webp"
      }
    ]
  },
  {
    "title": "Drumir",
    "tags": [
      "demo"
    ],
    "shortDescription": "World exploration multiplayer game based on DCC by Matt Dinniman",
    "longDescription": "World exploration multiplayer game based on DCC by Matt Dinniman\n\nIn development right now, looking for 2nd artist for this project.\n2026",
    "preview": "gallery/g14/preview.mp4",
    "fullsizePreview": "gallery/g14/fullsize_preview.webm",
    "media": [
      "gallery/g14/1.webm",
      "gallery/g14/2.mp4"
    ],
    "previewAsset": {
      "src": "gallery/g14/preview.mp4",
      "kind": "video",
      "width": 1920,
      "height": 1080,
      "wide": "gallery/g14/opt/preview-960.mp4",
      "wideW": 960,
      "narrow": "gallery/g14/opt/preview-640.mp4",
      "narrowW": 640,
      "poster": "gallery/g14/opt/preview-poster.webp",
      "thumb": "gallery/g14/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g14/fullsize_preview.webm",
      "kind": "video",
      "width": 1920,
      "height": 1080,
      "poster": "gallery/g14/opt/fullsize-poster.webp",
      "thumb": "gallery/g14/opt/fullsize-thumb.webp"
    },
    "mediaAssets": [
      {
        "src": "gallery/g14/1.webm",
        "kind": "video",
        "width": 1920,
        "height": 1080,
        "wide": "gallery/g14/opt/m1-960.mp4",
        "wideW": 960,
        "narrow": "gallery/g14/opt/m1-640.mp4",
        "narrowW": 640,
        "poster": "gallery/g14/opt/m1-poster.webp",
        "thumb": "gallery/g14/opt/m1-thumb.webp"
      },
      {
        "src": "gallery/g14/2.mp4",
        "kind": "video",
        "width": 1920,
        "height": 1080,
        "wide": "gallery/g14/opt/m2-960.mp4",
        "wideW": 960,
        "narrow": "gallery/g14/opt/m2-640.mp4",
        "narrowW": 640,
        "poster": "gallery/g14/opt/m2-poster.webp",
        "thumb": "gallery/g14/opt/m2-thumb.webp"
      }
    ]
  },
  {
    "title": "",
    "tags": [
      "game"
    ],
    "shortDescription": "Snippet of a game for Godot Wild Jam #51",
    "longDescription": "",
    "preview": "gallery/g15/preview.mp4",
    "fullsizePreview": "gallery/g15/fullsize_preview.mp4",
    "media": [],
    "previewAsset": {
      "src": "gallery/g15/preview.mp4",
      "kind": "video",
      "width": 400,
      "height": 224,
      "wide": "gallery/g15/opt/preview-400.mp4",
      "wideW": 400,
      "poster": "gallery/g15/opt/preview-poster.webp",
      "thumb": "gallery/g15/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g15/fullsize_preview.mp4",
      "kind": "video",
      "width": 1920,
      "height": 1080,
      "poster": "gallery/g15/opt/fullsize-poster.webp",
      "thumb": "gallery/g15/opt/fullsize-thumb.webp"
    },
    "mediaAssets": []
  },
  {
    "title": "",
    "tags": [
      "software"
    ],
    "shortDescription": "3D hyperrealistic maze generation backtracking algorithm in Unreal Engine 5",
    "longDescription": "3D hyperrealistic maze generation backtracking algorithm in Unreal Engine 5.\n\nFeed it an image, and it spits out 3d realistic maze based on that image.\n\nSource: https://github.com/fqqf/backtracking-3d-generator",
    "preview": "gallery/g16/preview.png",
    "fullsizePreview": "",
    "media": [
      "gallery/g16/1.jpg",
      "gallery/g16/2.jpg"
    ],
    "previewAsset": {
      "src": "gallery/g16/preview.png",
      "kind": "image",
      "width": 1933,
      "height": 986,
      "wide": "gallery/g16/opt/preview-960.webp",
      "wideW": 960,
      "narrow": "gallery/g16/opt/preview-640.webp",
      "narrowW": 640,
      "thumb": "gallery/g16/opt/preview-thumb.webp"
    },
    "fullsizeAsset": null,
    "mediaAssets": [
      {
        "src": "gallery/g16/1.jpg",
        "kind": "image",
        "width": 1167,
        "height": 1120,
        "wide": "gallery/g16/opt/m1-960.webp",
        "wideW": 960,
        "narrow": "gallery/g16/opt/m1-640.webp",
        "narrowW": 640,
        "thumb": "gallery/g16/opt/m1-thumb.webp"
      },
      {
        "src": "gallery/g16/2.jpg",
        "kind": "image",
        "width": 1090,
        "height": 836,
        "wide": "gallery/g16/opt/m2-960.webp",
        "wideW": 960,
        "narrow": "gallery/g16/opt/m2-640.webp",
        "narrowW": 640,
        "thumb": "gallery/g16/opt/m2-thumb.webp"
      }
    ]
  },
  {
    "title": "",
    "tags": [
      "demo"
    ],
    "shortDescription": "Demo of rimworld-like game made to test AI for Drumir",
    "longDescription": "Demo of rimworld-like game made to test AI for Drumir\n\nClosed source.",
    "preview": "gallery/g18/preview.mp4",
    "fullsizePreview": "gallery/g18/fullsize_preview.mp4",
    "media": [
      "gallery/g18/1.jpg",
      "gallery/g18/2.mp4"
    ],
    "previewAsset": {
      "src": "gallery/g18/preview.mp4",
      "kind": "video",
      "width": 1920,
      "height": 1080,
      "wide": "gallery/g18/opt/preview-960.mp4",
      "wideW": 960,
      "narrow": "gallery/g18/opt/preview-640.mp4",
      "narrowW": 640,
      "poster": "gallery/g18/opt/preview-poster.webp",
      "thumb": "gallery/g18/opt/preview-thumb.webp"
    },
    "fullsizeAsset": {
      "src": "gallery/g18/fullsize_preview.mp4",
      "kind": "video",
      "width": 1920,
      "height": 1080,
      "poster": "gallery/g18/opt/fullsize-poster.webp",
      "thumb": "gallery/g18/opt/fullsize-thumb.webp"
    },
    "mediaAssets": [
      {
        "src": "gallery/g18/1.jpg",
        "kind": "image",
        "width": 1280,
        "height": 839,
        "wide": "gallery/g18/opt/m1-960.webp",
        "wideW": 960,
        "narrow": "gallery/g18/opt/m1-640.webp",
        "narrowW": 640,
        "thumb": "gallery/g18/opt/m1-thumb.webp"
      },
      {
        "src": "gallery/g18/2.mp4",
        "kind": "video",
        "width": 1920,
        "height": 1080,
        "wide": "gallery/g18/opt/m2-960.mp4",
        "wideW": 960,
        "narrow": "gallery/g18/opt/m2-640.mp4",
        "narrowW": 640,
        "poster": "gallery/g18/opt/m2-poster.webp",
        "thumb": "gallery/g18/opt/m2-thumb.webp"
      }
    ]
  }
];
