"""Build gallery-data.js from gallery/g* directories."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
GALLERY = ROOT / "gallery"
OUTPUT = ROOT / "gallery-data.js"
MEDIA_EXTENSIONS = {
    ".avif", ".bmp", ".gif", ".jpeg", ".jpg", ".m4v", ".mov",
    ".mp4", ".ogg", ".png", ".svg", ".webm", ".webp",
}


def natural_key(path: Path) -> list[object]:
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", path.name)]


def read_metadata(folder: Path) -> tuple[list[str], str, str, str]:
    metadata = folder / "description.txt"
    if not metadata.is_file():
        return [], "", "", ""
    lines = metadata.read_text(encoding="utf-8-sig").splitlines()
    tag_line = lines[0] if lines else ""
    title = lines[1].strip() if len(lines) > 1 else ""
    short_description = lines[2].strip() if len(lines) > 2 else ""
    long_description = "\n".join(lines[3:]).strip() if len(lines) > 3 else ""
    tags = [tag.lstrip("#").lower() for tag in re.split(r"[\s,]+", tag_line) if tag.lstrip("#")]
    return tags, title, short_description, long_description


def build_items() -> list[dict[str, object]]:
    items = []
    folders = sorted((path for path in GALLERY.glob("g*") if path.is_dir()), key=natural_key)
    for folder in folders:
        preview_files = sorted(
            path for path in folder.iterdir()
            if path.is_file() and path.stem.lower() == "preview" and path.suffix.lower() in MEDIA_EXTENSIONS
        )
        if not preview_files:
            continue
        preview = preview_files[0]
        media = sorted(
            (
                path for path in folder.iterdir()
                if path.is_file() and path.stem.isdigit() and path.suffix.lower() in MEDIA_EXTENSIONS
            ),
            key=lambda path: (int(path.stem), path.suffix.lower()),
        )
        tags, title, short_description, long_description = read_metadata(folder)
        items.append({
            "title": title,
            "tags": tags,
            "shortDescription": short_description,
            "longDescription": long_description,
            "preview": preview.relative_to(ROOT).as_posix(),
            "media": [path.relative_to(ROOT).as_posix() for path in media],
            "hidePreview": (folder / "hide_preview").is_file(),
        })
    return items


def main() -> None:
    items = build_items()
    payload = json.dumps(items, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by generate-gallery.py. Do not edit by hand.\n"
        f"window.galleryItems = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.name} with {len(items)} items")


if __name__ == "__main__":
    main()
